# Generated by Django 3.2.8 on 2021-10-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211008_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.category'),
        ),
    ]
