# Generated by Django 3.2.8 on 2021-10-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_balance_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance_initial',
        ),
    ]
