# Generated by Django 3.2.8 on 2021-10-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_balance_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launch',
            options={'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AlterField(
            model_name='launch',
            name='value_in_cents',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Saldo Atual'),
        ),
    ]
