# Generated by Django 3.2.8 on 2021-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20211008_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_initial',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Saldo Inicial'),
        ),
    ]
