# Generated by Django 3.2.8 on 2021-10-08 17:36

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211008_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='value_in_cents_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='launch',
            name='value_in_cents',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=14, verbose_name='Saldo Atual'),
        ),
    ]
