# Generated by Django 3.2.8 on 2021-10-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': 'Aporte', 'verbose_name_plural': 'Aportes'},
        ),
    ]
