# Generated by Django 3.2.8 on 2021-10-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_alter_revenue_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='year',
            new_name='year_at',
        ),
    ]
