# Generated by Django 3.2.8 on 2021-10-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_rename_year_revenue_year_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='price',
            new_name='value_in_cents',
        ),
    ]
