# Generated by Django 3.2.8 on 2021-10-08 17:40

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_rename_price_revenue_value_in_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='value_in_cents_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='value_in_cents',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=14, verbose_name='Valor do aporte'),
        ),
    ]
