# Generated by Django 3.2.8 on 2021-10-09 00:05

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0014_auto_20211008_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_in_cents_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar')], default='BRL', editable=False, max_length=3)),
                ('value_in_cents', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=14, verbose_name='Valor da retirada')),
                ('month_at', models.CharField(choices=[('jan', 'Janeiro'), ('fev', 'Fevereiro'), ('mar', 'Março'), ('abr', 'Abril'), ('mai', 'Maio'), ('jun', 'Junho'), ('jul', 'Julho'), ('ago', 'Agosto'), ('set', 'Setembro'), ('out', 'Outubro'), ('nov', 'Novembro'), ('dez', 'Dezembro')], max_length=191, verbose_name='Mês Ativo')),
                ('year_at', models.CharField(max_length=191, verbose_name='Ano Ativo')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Retiradas',
            },
        ),
    ]
