# Generated by Django 3.2.8 on 2021-10-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='description',
            field=models.CharField(default=None, max_length=191, null=True, verbose_name='Descrição'),
        ),
    ]
